name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  actions: read
  checks: write # needed for report upload
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: debug
      run: find . -iname '*.trx'
    - name: Test Report
      uses: dorny/test-reporter@v1.9.1 # requires write permission (above)
      if: success() || failure()
      with:
        name: Tests
        path: ./**/test-results.trx
        reporter: dotnet-trx
